import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers} from './providers'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import process from 'process';
import config from './scripts/config'
config.set_host(process.env.ATTENTION_HOST ?? "localhost:8008")


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}><Providers>{children}</Providers></body>
    </html>
  );
}
