import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers} from './providers'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import process from 'process';
import config from './scripts/config'
import Tabs from "./components/Tabs";

console.log(`layout init - ATTENTION_HOST=${process.env.ATTENTION_HOST}`)
config.set_host(process.env.ATTENTION_HOST ?? "localhost:8008")


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' overflow-x-clip'} suppressHydrationWarning={true}><Providers>
        <Tabs></Tabs>
        {children}</Providers></body>
    </html>
  );
}
